server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/16ban?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: com.ffl.ahydboot.bean
  mapper-locations: classpath*:mapper/*.xml

#showSql
logging:
  level:
    com.ffl.ahydboot.mapper: DEBUG
